interval: 1
timeout: 30
services:
  - name: clubs
    url: http://clubs/graphql
  - name: events
    url: http://events/graphql
  # - name: discussion
  #   url: http://discussion/graphql
  - name: users
    url: http://users/graphql
  - name: interfaces
    url: http://interfaces/graphql
