interval: 1
timeout: 30
services:
  - name: auth
    url: http://auth/graphql
  - name: clubs
    url: http://clubs/graphql
  - name: events
    url: http://events/graphql
  - name: discussion
    url: http://discussion/graphql
  - name: mailing
    url: http://mailing/graphql
